/*
  Copyright 2015 Google Inc. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORFConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ORFConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dismiss.
        /// </summary>
        internal static string StringButtonDismiss {
            get {
                return ResourceManager.GetString("StringButtonDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop.
        /// </summary>
        internal static string StringButtonStop {
            get {
                return ResourceManager.GetString("StringButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion stopped by user: {0} files converted..
        /// </summary>
        internal static string StringConversionStopped {
            get {
                return ResourceManager.GetString("StringConversionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified destination folder does not exist. Do you wish to create it?.
        /// </summary>
        internal static string StringCreateDestination {
            get {
                return ResourceManager.GetString("StringCreateDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done: {0} files successfully converted..
        /// </summary>
        internal static string StringDone {
            get {
                return ResourceManager.GetString("StringDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the specified destination folder..
        /// </summary>
        internal static string StringErrorCreateDestination {
            get {
                return ResourceManager.GetString("StringErrorCreateDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destination folder or invalid destination path specified. Please select or enter a destination folder..
        /// </summary>
        internal static string StringErrorDestination {
            get {
                return ResourceManager.GetString("StringErrorDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} ORF files to be processed..
        /// </summary>
        internal static string StringGatheringEnd {
            get {
                return ResourceManager.GetString("StringGatheringEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering list of files....
        /// </summary>
        internal static string StringGatheringStart {
            get {
                return ResourceManager.GetString("StringGatheringStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file: .
        /// </summary>
        internal static string StringProcessingFile {
            get {
                return ResourceManager.GetString("StringProcessingFile", resourceCulture);
            }
        }
    }
}
